#!/usr/bin/env bash
set -euo pipefail

usage() {
  cat << 'USAGE'
Discover projects that appear to use this Codex workflow.

Usage:
  ./scripts/discover-codex-projects.sh [--root <dir>]... [--write <file>] [--include-source]

Options:
  --root <dir>       Directory to scan. Can be passed multiple times.
                     Defaults to the parent directory of this repository.
  --write <file>     Write discovered downstream project paths to a target list file.
  --include-source   Include this source repository in printed results and --write output.
  -h, --help         Show this help message.

Detection:
  - bootstrapped layout: <project>/.codex/AGENTS.md
  - root layout:        <project>/AGENTS.md with <project>/skills/routing
USAGE
}

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SOURCE_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
DEFAULT_SCAN_ROOT="$(dirname "$SOURCE_ROOT")"

SCAN_ROOTS=()
WRITE_FILE=""
INCLUDE_SOURCE=0

while (($# > 0)); do
  case "$1" in
    --root)
      if [[ $# -lt 2 ]]; then
        echo "[ERROR] --root requires a directory path." >&2
        exit 1
      fi
      SCAN_ROOTS+=("$2")
      shift 2
      ;;
    --write)
      if [[ $# -lt 2 ]]; then
        echo "[ERROR] --write requires a file path." >&2
        exit 1
      fi
      WRITE_FILE="$2"
      shift 2
      ;;
    --include-source)
      INCLUDE_SOURCE=1
      shift
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    -*)
      echo "[ERROR] Unknown option: $1" >&2
      usage
      exit 1
      ;;
    *)
      echo "[ERROR] Unexpected argument: $1" >&2
      usage
      exit 1
      ;;
  esac
done

if [[ "${#SCAN_ROOTS[@]}" -eq 0 ]]; then
  SCAN_ROOTS=("$DEFAULT_SCAN_ROOT")
fi

abs_path() {
  local path="$1"
  if [[ -d "$path" ]]; then
    (cd "$path" && pwd)
    return 0
  fi
  return 1
}

is_source_root() {
  local project_dir="$1"
  [[ "$project_dir" == "$SOURCE_ROOT" ]]
}

print_result() {
  local project_dir="$1"
  local layout="$2"
  local marker="$3"

  printf "%s\t%s\t%s\n" "$project_dir" "$layout" "$marker"
}

results_file="$(mktemp)"
trap 'rm -f "$results_file"' EXIT

for root in "${SCAN_ROOTS[@]}"; do
  if ! scan_root="$(abs_path "$root")"; then
    echo "[WARN] Skipping missing scan root: $root" >&2
    continue
  fi

  while IFS= read -r agents_file; do
    project_dir="$(cd "$(dirname "$agents_file")/.." && pwd)"
    if [[ "$INCLUDE_SOURCE" -ne 1 ]] && is_source_root "$project_dir"; then
      continue
    fi
    print_result "$project_dir" ".codex" "$agents_file" >> "$results_file"
  done < <(find "$scan_root" \
    \( -name .git -o -name node_modules -o -name .venv -o -name vendor -o -name build -o -name dist -o -name DerivedData -o -name Library -o -name .Trash -o -name .cache -o -name .gradle -o -name .npm -o -name .cargo -o -name .rustup -o -name Pods \) -prune \
    -o -path "*/.codex/AGENTS.md" -type f -print 2>/dev/null)

  while IFS= read -r agents_file; do
    project_dir="$(cd "$(dirname "$agents_file")" && pwd)"
    if [[ ! -d "$project_dir/skills/routing" ]]; then
      continue
    fi
    if [[ "$INCLUDE_SOURCE" -ne 1 ]] && is_source_root "$project_dir"; then
      continue
    fi
    print_result "$project_dir" "root" "$agents_file" >> "$results_file"
  done < <(find "$scan_root" \
    \( -name .git -o -name node_modules -o -name .venv -o -name vendor -o -name build -o -name dist -o -name DerivedData -o -name Library -o -name .Trash -o -name .cache -o -name .gradle -o -name .npm -o -name .cargo -o -name .rustup -o -name Pods \) -prune \
    -o -name AGENTS.md -type f -not -path "*/.codex/AGENTS.md" -print 2>/dev/null)
done

sort -u "$results_file" -o "$results_file"

echo "Discovered Codex projects:"
if [[ ! -s "$results_file" ]]; then
  echo "- none"
else
  while IFS=$'\t' read -r project_dir layout marker; do
    printf -- "- %s (%s layout, marker: %s)\n" "$project_dir" "$layout" "$marker"
  done < "$results_file"
fi

if [[ -n "$WRITE_FILE" ]]; then
  mkdir -p "$(dirname "$WRITE_FILE")"
  {
    printf "# Codex downstream target projects\n"
    printf "# Generated by scripts/discover-codex-projects.sh\n"
    while IFS=$'\t' read -r project_dir _layout _marker; do
      printf "%s\n" "$project_dir"
    done < "$results_file"
  } > "$WRITE_FILE"
  echo
  echo "Wrote target list: $WRITE_FILE"
fi
